language: java

cache:
  directories:
    - $HOME/.m2

install: true
script:
  - mvn clean package
after_success:
   - mvn jacoco:report coveralls:report
   - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
