language: java

cache:
  directories:
    - $HOME/.m2

install: true
script:
  - mvn clean package
after_success:
   - mvn jacoco:report coveralls:report
   - mvn com.blackducksoftware.integration:hub-maven-plugin:2.0.0:build-bom -Dhub.output.directory=. -Dhub.deploy.bdio=false
   - bash <(curl -s https://copilot.blackducksoftware.com/bash/circle) ./*_bdio.jsonld
