language: java

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - akamen@blackducksoftware.com
      - jrichard@blackducksoftware.com
      - psantos@blackducksoftware.com
      - ekerwin@blackducksoftware.com

install: true
script:
  #skip tests for now since some of them require a hub server
  - mvn clean package -DskipTests=true
after_success:
  #- mvn test jacoco:report coveralls:report
